### ISSUE TITLE
Adding APK to releases?

### ISSUE THREAD

**Issue by IzzySoft** [fistons/TinyTinyFeed#24] opened 2017-11-01 20:25 UTC
Would you mind attaching an `.apk` to your releases – for folks w/o Playstore? I'd then offer to take it into [my F-Droid compatible repo](https://apt.izzysoft.de/fdroid).

Taking a look at your gradle file it seems your app could also make it into the official repo. Would you like that? (Getting into mine is faster and usually also means faster updates – but making it into the official repo is even better, for many reasons such as prestige for you and making your users feel "more safe" due to the stricter rules there.)

**Comment by fistons** [comment] 2017-11-03 12:08
It seems to be a great idea! I'll do it with the next release.

And yes, I would like to make it to both your repo and the official one.

Thanks!

**Comment by IzzySoft** [comment] 2017-12-11 14:30
I've opened [an RFP for you](https://gitlab.com/fdroid/rfp/issues/441) (Request For Packaging) with the official repository. To further its processing, you will need to **define a license for your project.** Please also check with their [inclusion citeria](https://f-droid.org/wiki/page/Inclusion_Policy) to make sure we didn't miss something here. That done, please let me know (by updating this issue) so I can tick the missing check-mark over there. Of course you're also welcome to "chime in" with the request at GitLab directly.

Also, once you've attached an `.apk` please let me know, so I can add it to my repo – in case your app is not yet listed at the official repo then. I try to keep overlappings low to avoid confusion at the users' end (signatures won't match, as F-Droid builds from sources and self-signs the package) – so once an app made it into the official repo, it shall live there (exceptions are made, especially if for some reason F-Droid no longer can provide updates).

**Comment by fistons** [comment] 2017-12-13 08:22
I just added the license file and now everything should be fine!

I will try to create a release this week end (or the next, I'm pretty busy those days) and this time, add the .apk file with it!

Thanks a lot for your help!

**Comment by IzzySoft** [comment] 2017-12-13 09:52
Thanks, @fistons – I've updated the RFP accordingly. Should now be ready to be processed. Given that the F-Droid team is a bit understaffed currently, it might take a little nonetheless. But I'd say them catching up with your just announced release is a good guess.

Looking forward to that release and its APK. Should F-Droid be ready then (or at least have approved the RFP and have the listing pending), I'd refrain from putting it into my repo additionally (still good to have the APK there just in case, so I could pick up anytime). Should the RFP be still unprocessed, I'd of course pick it up. Just ping me here again when the release is there.

Big thumbs up to you, and thanks a lot for your good support (and, of course, app)!

**Comment by IzzySoft** [comment] 2017-12-16 14:22
@fistons Minor issue on F-Droid requiring your help, please see [here](https://gitlab.com/fdroid/rfp/issues/441#note_51670818) (basically requiring a small adjustment to `build.gradle` if I understand that correctly). Could you please check?

**Comment by fistons** [comment] 2017-12-23 17:13
Everything should be fine now!

**Comment by IzzySoft** [comment] 2017-12-27 09:09
From my end, indeed! You can find your app [here](https://apt.izzysoft.de/fdroid/index/apk/org.poopeeland.tinytinyfeed) now. But for the main repo, there still seems to be an issue. Quoting relan:

> build.gradle must reference Google Maven repo here:

```
repositories {
    mavenCentral()
    jcenter()
}
dependencies {
    classpath 'com.android.tools.build:gradle:3.0.0'
}
```

> Otherwise it won't compile with command line tools (Gradle will fail to find `com.android.tools.build:gradle:3.0.0`).

Could you please check and fix?

**Comment by fistons** [comment] 2017-12-27 16:55
It is already fixed: https://github.com/fistons/TinyTinyFeed/blob/remote/TinyTinyFeed/build.gradle

**Comment by IzzySoft** [comment] 2017-12-27 17:55
Thanks again, Eric! I've notified the F-Droid crew to try again. Fingers crossed!

**Comment by relan** [comment] 2017-12-28 06:43
Hi,

F-Droid maintainer here. I'd like TinyTinyFeed to be updated automatically on F-Droid. Currently this won't work because versionCode is in build.gradle, while versionName and applicationId (package) are in AndroidManifest.xml. Could you please put all 3 into either build.gradle or AndroidManifest.xml?

**Comment by fistons** [comment] 2017-12-28 16:49
Hi,

It's done!

Thanks!

**Comment by IzzySoft** [comment] 2017-12-28 19:22
@fistons thanks!

@relan Please let us know when it's added on your end – and whether it's using Eric's signature or F-Droid's.

**Comment by relan** [comment] 2017-12-30 15:52
Added with F-Droid's signature. Thank you both, guys!

No idea when TinyTinyFeed will be available on F-Droid, buildserver currently has problems.

**Comment by IzzySoft** [comment] 2017-12-31 03:32
Thank **you** @relan ! And hopefully, the buildserver problems are solved soon and not to come back next year. They were a bit too frequent this year already, that should suffice for 5 years now :wink:

**Comment by fistons** [comment] 2017-12-31 09:47
Thanks to both of you! I'm closing the issue now. Don't hesitate to re-open it if there is a problem 😉

**Closed by fistons** 2017-12-31 09:47 UTC

**Comment by relan** [comment] 2018-02-28 05:58
We're having a problem with 1.12.1:

    Could not find org.jetbrains.trove4j:trove4j:20160824

The full build log is here: https://f-droid.org/wiki/page/org.poopeeland.tinytinyfeed/lastbuild_23

Steps to reproduce:

1. `cd TinyTinyFeed`
2. `gradle assembleRelease`

This happens because `org.jetbrains.trove4j:trove4j` is in JCenter, see https://stackoverflow.com/questions/45818613/trove4j-library-cannot-be-resolved

The fix:

```patch
diff --git a/TinyTinyFeed/build.gradle b/TinyTinyFeed/build.gradle
index 2902be7..db06983 100644
--- a/TinyTinyFeed/build.gradle
+++ b/TinyTinyFeed/build.gradle
@@ -1,6 +1,7 @@
 buildscript {
     repositories {
         mavenCentral()
+        jcenter()
         google()
     }
     dependencies {
```

**Comment by fistons** [comment] 2018-02-28 09:43
Thanks for reporting! I will take care of it as soon as possible!

**Comment by fistons** [comment] 2018-03-01 08:21
Should be fixed! :)

**Comment by relan** [comment] 2018-03-01 10:53
Thanks! The next version will be pulled by F-Droid automatically.
